services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # twig extension: links
    NewsBundle\Twig\Extension\NewsExtension:
        tags:
            - { name: twig.extension }

    # twig extension: relations
    NewsBundle\Twig\Extension\RelatedEntriesExtension:
        tags:
            - { name: twig.extension }

    # twig extension: video tag
    NewsBundle\Twig\Extension\VideoTagExtension:
        tags:
            - { name: twig.extension }