imports:
    - { resource: services/*.yml }

services:

    # tool: installer
    news.tool.installer:
        class: NewsBundle\Tool\Install
        arguments:
            - '@pimcore_admin.serializer'

    # configuration
    news.configuration:
        class: NewsBundle\Configuration\Configuration

    # area brick
    news.area.brick.form:
        class: NewsBundle\Document\Areabrick\News\News
        arguments:
            - '@news.configuration'
            - '@news.manager.entry_types'
            - '@pimcore.translator'
        tags:
            - { name: pimcore.area.brick, id: news }

    # manager entry types
    news.manager.entry_types:
        class: NewsBundle\Manager\EntryTypeManager
        arguments:
            - '@news.configuration'

    # abstract generator entry links
    news.generator.abstract.link:
        class: NewsBundle\Generator\AbstractLinkGenerator
        abstract: true
        arguments:
            - '@router'
            - '@news.manager.entry_types'

    # generator entry links
    news.generator.link:
        parent: news.generator.abstract.link
        class: NewsBundle\Generator\LinkGenerator

    # abstract generator related entries
    news.generator.abstract.related_entries:
        class: NewsBundle\Generator\AbstractRelatedEntriesGenerator
        abstract: true

    # generator related entries
    news.generator.related_entries:
        parent: news.generator.abstract.related_entries
        class: NewsBundle\Generator\RelatedEntriesGenerator

    # abstract generator head meta
    news.generator.abstract.head_meta:
        class: NewsBundle\Generator\AbstractHeadMetaGenerator
        abstract: true
        arguments:
            - '@news.generator.link'

    # generator head meta
    news.generator.head_meta:
        parent: news.generator.abstract.head_meta
        class: NewsBundle\Generator\HeadMetaGenerator

